

const blogs = [ 
    {
        id:1,
        image:"images/dietitian3-blog-pic1.png",
        iconHurt:"images/icon-hurt.png",
        iconClock:"images/clock.png",
        iconUser:"images/user.png",
        eat:"Breakfasts",
        diet:"Diet tips",
        recept:"Recipies",
        title:"Luptatum zzril delenit augue",
        text:"Dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
        name:"admin",
        date:"October 20, 2021",
        readMore:" Read more...",
    },
    {
        id:2,
        image:"images/dietitian3-blog-pic2.png",
        iconHurt:"images/icon-hurt.png",
        iconClock:"images/clock.png",
        iconUser:"images/user.png",
        advice:"Advice",
        eat:"Breakfasts",
        recept:"Recipies",
        title:"Tation ullamcorper suscipit",
        text:"Eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
        name:"admin",
        date:"February 9, 2021",
        readMore:" Read more...",
    },
    {
        id:3,
        image:"images/dietitian3-blog-pic3.png",
        iconHurt:"images/icon-hurt.png",
        iconClock:"images/clock.png",
        iconUser:"images/user.png",
        advice:"Advice",
        diet:"Diet tips",
        excercises:"Excercises",
        title:"Luptatum zzril delenit augue",
        text:"Dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
        name:"admin",
        date:"March 12, 2020",
        readMore:" Read more...",
    },
    {
        id:4,
        image:"images/dietitian3-blog-pic4.png",
        iconHurt:"images/icon-hurt.png",
        iconClock:"images/clock.png",
        iconUser:"images/user.png",
        diet:"Diet tips",
        lunch:"Lunch",
        recept:"Recipies",
        title:"Lobortis nisl ut aliquip",
        text:" Labore et dolore magna aliquyam erat, sed diam voluptua.",
        name:"admin",
        date:"Juanyre 3, 2021",
        readMore:" Read more...",
    },

]

export default blogs